import type { Metadata } from "next";

import Footer from "./components/Footer";
import Navbar from "./components/navbar";
import { Provider } from "react-redux";

import "./globals.css";
import { store } from "@/lib/store/Slices/Store";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className='bg-gray-50'>
				<Provider store={store}>
					<Navbar />
					<div className='pt-23.5 pb-7 '>{children}</div>
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
