import type { Metadata } from "next";

import Footer from "./components/Footer";
import Navbar from "./components/navbar";
import "./globals.css";
import ClientProvider from "./components/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <ClientProvider>
          <Navbar />
          <div className="pt-23.5 ">{children}</div>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
